---
- name: Install Apache
  package:
    name: httpd
    state: present

- name: Create document root
  file:
    path: "{{ document_root }}"
    state: directory
    owner: apache
    group: apache
    mode: '0755'

- name: Deploy test index page
  copy:
    content: "Welcome to {{ server_name }} environment\n"
    dest: "{{ document_root }}/index.html"
    owner: apache
    group: apache
    mode: '0644'

- name: Start and enable Apache
  service:
    name: httpd
    state: started
    enabled: yes

- name: Deploy VirtualHost configuration
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/{{ server_name }}.conf
  notify: Restart Apache

- name: Remove default Apache welcome config
  file:
    path: /etc/httpd/conf.d/welcome.conf
    state: absent
  notify: Restart Apache


